name = "cf-dioxus-server-fn"
main = "build/worker/shim.mjs"
compatibility_date = "2025-07-07"

[build]
command = "./dioxus-build && cargo install -q worker-build && worker-build --release"

[assets]
directory = "../cf-dioxus/target/dx/cf-dioxus/release/web/public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [ "/api/*" ]

[observability.logs]
enabled = true
