[application]

[web]
# Workers does not use the pre-compressed files
pre_compress = false

[web.app]

# HTML title tag content
title = "multiply"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
