#!/bin/sh

set -e -x

dx bundle --release --platform web "$@"

# Firefox attempts to prefetch the favicon from /favicon.ico - add the icon to
# the top-level so it does not activate a Worker instance.
cp assets/favicon.ico target/dx/cf-dioxus/release/web/public/favicon.ico

# Add a robots.txt so crawlers do not activate a Worker. Change this if you
# want crawlers to index your site.
cat > target/dx/cf-dioxus/release/web/public/robots.txt <<EOF
User-agent: *
Disallow: /
EOF

# Files in the assets directory include a content-based hash in the name.
# Allow caches to provide these files for up to 6 months without revalidating.
# See https://developers.cloudflare.com/workers/static-assets/headers/
cat > target/dx/cf-dioxus/release/web/public/_headers <<EOF
/assets/*
    Cache-Control: public, max-age=15552000, immutable
EOF
